version: "3.8"

services:
  posts-backend:
    container_name: 'jobhunt-posts-backend'
    command: sh "docker/commands/run-backend.sh"
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/backend/
    ports:
      - "3000:3000"
    networks:
      - shared-service-network
    depends_on:
      posts-postgres:
        condition: service_healthy
      posts-redis:
        condition: service_started

  posts-postgres:
    container_name: 'jobhunt-posts-postgres'
    image: postgres:15.4-alpine
    volumes:
      - post_postgres_data:/var/lib/postgresql/data/
    networks:
      - shared-service-network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

  posts-redis:
    container_name: 'jobhunt-posts-redis'
    image: redis:7.2-alpine
    networks:
      - shared-service-network

networks:
  shared-service-network:
    external: true
volumes:
  post_postgres_data: