apiVersion: v1
kind: Service
metadata:
  name: users-backend
  labels:
      service: jobhunt-users-backend

spec:
    selector:
        service: jobhunt-users-backend
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobhunt-users-backend
  labels:
      service: jobhunt-users-backend

spec:
    replicas: 1
    selector:
        matchLabels:
            service: jobhunt-users-backend
    template:
        metadata:
            labels:
                service: jobhunt-users-backend
        spec:
            containers:
              - name: jobhunt-backend
                image: ml06py/jobhunt-users-backend:latest
                imagePullPolicy: Always
                ports:
                    - containerPort: 8000
                command: ["/bin/sh"]
                args: ["-c", "sh docker/commands/run-backend.sh"]
                envFrom:
                  - configMapRef:
                      name: jobhunt-user-env