apiVersion: v1
kind: Service
metadata:
  name: posts-backend
  labels:
    service: jobhunt-posts-backend

spec:
  selector:
    service: jobhunt-posts-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobhunt-posts-backend
  labels:
    service: jobhunt-posts-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      service: jobhunt-posts-backend
  template:
    metadata:
      labels:
        service: jobhunt-posts-backend
    spec:
      containers:
        - name: jobhunt-posts
          image: ml06py/jobhunt-posts-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["/bin/sh"]
          args: ["-c", "sh docker/commands/run-backend.sh"]
          envFrom:
            - configMapRef:
                name: jobhunt-posts-env