apiVersion: v1
kind: Service

metadata:
  name: posts-postgres
  labels:
    service:  users-postgres

spec:
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: jobhunt-posts-postgres
  labels:
    service: posts-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      service: posts-postgres
  template:
    metadata:
      labels:
        service: posts-postgres
    spec:
      containers:
        - name: jobhunt-posts-postgres
          image: postgres:15.4-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: jobhunt-posts-env