version: "3.8"

services:
  users-backend:
    container_name: 'jobhunt-users-backend'
    command: sh "docker/commands/run-backend.sh"
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/backend/
    depends_on:
        users-postgres:
            condition: service_healthy
    networks:
      - shared-service-network

  users-postgres:
    container_name: 'jobhunt-users-postgres'
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - shared-service-network
    env_file:
      - env/pg.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  shared-service-network:
    external: true

volumes:
    postgres_data:
